// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDrivenHotel.DAL;

#nullable disable

namespace TestDrivenHotel.DAL.Migrations
{
    [DbContext(typeof(HotelRoomsDB))]
    [Migration("20240125144310_UpdatedFunctionalyOfDb")]
    partial class UpdatedFunctionalyOfDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestDrivenHotel.DAL.HotelRoom", b =>
                {
                    b.Property<int>("RoomNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomNumber"));

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("int");

                    b.Property<int>("PricePerNight")
                        .HasColumnType("int");

                    b.HasKey("RoomNumber");

                    b.ToTable("HotelRooms");

                    b.HasData(
                        new
                        {
                            RoomNumber = 1,
                            IsBooked = false,
                            NumberOfBeds = 1,
                            PricePerNight = 1000
                        },
                        new
                        {
                            RoomNumber = 2,
                            IsBooked = false,
                            NumberOfBeds = 2,
                            PricePerNight = 2000
                        },
                        new
                        {
                            RoomNumber = 3,
                            IsBooked = false,
                            NumberOfBeds = 3,
                            PricePerNight = 3000
                        },
                        new
                        {
                            RoomNumber = 4,
                            IsBooked = false,
                            NumberOfBeds = 4,
                            PricePerNight = 4000
                        },
                        new
                        {
                            RoomNumber = 5,
                            IsBooked = false,
                            NumberOfBeds = 5,
                            PricePerNight = 5000
                        },
                        new
                        {
                            RoomNumber = 6,
                            IsBooked = false,
                            NumberOfBeds = 6,
                            PricePerNight = 6000
                        },
                        new
                        {
                            RoomNumber = 7,
                            IsBooked = false,
                            NumberOfBeds = 7,
                            PricePerNight = 7000
                        },
                        new
                        {
                            RoomNumber = 8,
                            IsBooked = false,
                            NumberOfBeds = 8,
                            PricePerNight = 8000
                        },
                        new
                        {
                            RoomNumber = 9,
                            IsBooked = false,
                            NumberOfBeds = 9,
                            PricePerNight = 9000
                        },
                        new
                        {
                            RoomNumber = 10,
                            IsBooked = false,
                            NumberOfBeds = 10,
                            PricePerNight = 10000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
